# Generated by Django 5.1.7 on 2025-03-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id_ingredient', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ingredient', models.CharField(max_length=255)),
                ('formuleChimique', models.CharField(max_length=255)),
                ('propriete', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id_joueur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=32)),
            ],
        ),
    ]
